version: "3"
services:
        web:
            image:   nickistre/centos-lamp
            restart: always
            ports:
                    - "3001:80"
            volumes:
                    - ./www:/var/www/html
                    - ./php.ini:/usr/local/etc/php/php.ini
            links:
                    - db
            networks:
                - default
        
        db:
            image: bingozhou/mysql5.7
            restart: always
            ports:
                    - "3306:3306"
            environment:
                MYSQL_DATABASE: uinfo
                MYSQL_USER: uinfo
                MYSQL_PASSWORD: oAds3!9a1
                MYSQL_ROOT_PASSWORD: CHINA_SUPER_PTE 
            volumes:
                - ./mysql/init/:/docker-entrypoint-initdb.d/
            networks:
                - default
